spring:
  application:
    name: githubconsumer
server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true

github:
  personal:
    token: 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
